#Expyriment 0.8.0 (Python 2.7.10), .xpe-file, coding: UTF-8
#date: Mon Aug 24 2015 21:36:20
#sha1: 4d698f
#modules: 
#display: size=(800, 600), window_mode=True, open_gl=2
#os: ('Linux', 'localhost.localdomain', '4.1.3-200.fc22.x86_64', '#1 SMP Wed Jul 22 19:51:58 UTC 2015', 'x86_64', 'x86_64')
Time,Type,Event,Value,Detail,Detail2
1162,design,log,
#design: #exp: interhemispheric reaction time
#design: block_cnt,block_id,trial_cnt,trial_id
1163,design,logged,
1163,Experiment,started
1404,stderr,received,'Traceback (most recent call last):'
1404,stderr,received,'  File "ihtt.py", line 47, in <module>'
1404,stderr,received,'    for block in exp.blocks():'
1404,stderr,received,"TypeError: 'list' object is not callable"
